version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-backend
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: leads
      POSTGRES_USER: leads
      POSTGRES_PASSWORD: leads
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
